# Site settings
title: 牧码人
email: li396858359@163.com
description: Android开发者一枚
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: 
github_username:  hkllzh

# Build settings
# markdown: maruku
markdown: redcarpet
# markdown: kramdown
markdown_ext: markdown
source:      .
destination: ./_deploy
# highlighter: pygments
highlighter: pygments