# Site settings
title: hkllzh
email: li396858359@163.com
description: description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  hkllzh

# Build settings
# markdown: maruku
markdown: kramdown
markdown_ext: markdown
source:      .
destination: ./_deploy1
# highlighter: pygments
highlighter: pygments